version: '3.0'

services:

  # nginx:
  #   image: nginx
  #   environment:
  #     - VIRTUAL_HOST=excurs-orel
  #   volumes:
  #     - ./nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
  #     - ../public_html/:/var/www/html/
  #   networks:
  #     - frontend
  #     - backend
    # depends_on:
    #   - wordpress

  # php:
  #   build:
  #     context: ./php
  #   volumes:
  #     - ./php/php.ini:/usr/local/etc/php/php.ini
  #     - ../public_html/:/var/www/html/
  #   networks:
  #     - backend
  #   depends_on:
  #     - mysql

  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ../public_html/:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    # command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    # ports:
    #   - 3306:3306
    environment:
      # MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    # ports:
    #   - '8080:80'
    environment:
      VIRTUAL_HOST: phpmyadmin.local
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - frontend
      - backend
    depends_on:
      - mysql

networks:
  frontend:
    external:
      name: proxy_proxy
  backend:

volumes:
  db_volume: